### ISSUE TITLE
CSS Text Wrapping

### ISSUE THREAD

**Issue by mosee101** [ddan9/webchat#5]
![1](https://user-images.githubusercontent.com/61285062/190031667-a297c597-ac29-4d67-95c4-3ba6d29f8cb4.png)

Any idea how to have the text wrap to the box?

**Comment by ddan9** [comment]
Do not quite understand. Are you trying to escape xmp to make the tags work? Trying to customize styles?

And if this is the fifth issue, where are the other 3?

**Comment by ddan9** [comment]
> ![1](https://user-images.githubusercontent.com/61285062/190031667-a297c597-ac29-4d67-95c4-3ba6d29f8cb4.png)
> 
> Any idea how to have the text wrap to the box?

Do not quite understand. Are you trying to escape xmp to make the tags work? Trying to customize styles?

And if this is the fifth issue, where are the other 3?

**Comment by mosee101** [comment]
I'm trying to manipulate the styles, I don't see any changes no matter what I modify. Must be a weird caching problem on my end.

I only opened 2 issues with you about this code, not sure why I see #5.

**Comment by ddan9** [comment]
> I'm trying to manipulate the styles, I don't see any changes no matter what I modify. Must be a weird caching problem on my end.
> 
> I only opened 2 issues with you about this code, not sure why I see #5.

When working with styles (and in general) I use incognito mode. It allows you to avoid caching and immediately see the results of changes

**Comment by ddan9** [comment]
By the way, I just remembered. Chat is used in our college between students, of which there are quite a lot. Just to disperse them, I made a primitive version of the rooms with separate chat instances in each

**Comment by mosee101** [comment]
I am using incognito mode, I am using 4 different browsers. Only way to see a clean refresh is to connect through TOR on Brave Browser.

*UPDATE*

The caching problem is with Cloudflare, it has nothing to do with me or your script. I was making the correct changes but it wasn't updating. All is working now. Thanks

**Comment by ddan9** [comment]
Do not quite understand. Are you trying to escape xmp to make the tags work? Trying to customize styles? And if this is the fifth issue, where are the other 3?
14.09.2022, 03:20, Mo < ***@***.*** ***@***.*** >
https://user-images.githubusercontent.com/61285062/190031667-a297c597-ac29-4d67-95c4-3ba6d29f8cb4.png 1
Any idea how to have the text wrap to the box?
